### ISSUE TITLE
ProfileControllerTest を Table Driven Test にリファクタリング

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#56]
## 概要

ProfileControllerTest を Table Driven Test にリファクタリングする。

イシュードリブン開発をやってみたかったため、作成

## TODO

- [x] showProfileのテスト を移行 https://github.com/sunakan/realworld-kotlin-springboot-jdbc/pull/57
- [x] follow のテストを移行 https://github.com/sunakan/realworld-kotlin-springboot-jdbc/pull/58
- [x] unfollow のテストを移行 https://github.com/sunakan/realworld-kotlin-springboot-jdbc/pull/59

**Comment by Msksgm** [comment]
マージ用 PR （ https://github.com/sunakan/realworld-kotlin-springboot-jdbc/pull/61 ） がマージされたので、クローズ
